---
title: "R-Intro"
author: "Tobi & Lukas"
date: "Aktualisiert: `r format(Sys.time(), '%d. %B %Y @ %H:%M Uhr')`"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
source("./init.R")
```

# Na, auch hier?

Was wie hier machen

## Wer sind wir

Leute!

## Was machen wir hier?

Dinge!

## Wieso das Ganze?

Hass!

# Was ist R?

## Voodoo

```{r, echo=TRUE, eval=FALSE}
mtcars %>%
  mutate(am = factor(am, levels = c(0, 1), labels = c("Automatik", "Manuell")),
         consumption = 235 / mpg) %>%
  ggplot(data = ., aes(x = hp, y = consumption, color = am)) +
  geom_smooth(aes(group = 1), method = lm, se = F, color = "gray") +
  geom_point(size = 3, alpha = .7) +
  scale_color_brewer(palette = "Set1") +
  labs(title = "Kraftstoffverbrauch",
       subtitle = "Verbrauch verschiedene PKW nach Leistung und Schaltung",
       x = "Leistung (PS)", y = "Verbrauch (L/100km)", color = "Schaltung")
```

## Schön

```{r, echo=FALSE}
mtcars %>%
  mutate(am = factor(am, levels = c(0, 1), labels = c("Automatik", "Manuell")),
         consumption = 235 / mpg) %>%
  ggplot(data = ., aes(x = hp, y = consumption, color = am)) +
  geom_smooth(aes(group = 1), method = lm, se = F, color = "gray") +
  geom_point(size = 3, alpha = .7) +
  scale_color_brewer(palette = "Set1") +
  labs(title = "Kraftstoffverbrauch",
       subtitle = "Verbrauch verschiedene PKW nach Leistung und Schaltung",
       x = "Leistung (PS)", y = "Verbrauch (L/100km)", color = "Schaltung")
```

